### PR TITLE
Updated the wrappers around the javascript api

### PR DESCRIPTION
**Pull request by niemyjski**
showMessages doesn't take content (according to the link below). Added showNewMessage.
http://docs.intercom.io/install-on-your-web-product/intercom-javascript-api

I didn't update the minified version or bower versions.

### CODE REVIEW

**Comment by niemyjski** [comment]
Is there any chance we can do a release for this as I need showNewMessage.

**Comment by gdi2290** [comment]
Just in case this happens I allowed old api to work too `$intercom('showMessages');` and `$intercom('`$intercom('showMessages');` ');` until I tag a new release
https://github.com/gdi2290/angular-intercom/blob/master/angular-intercom.js#L106

**Comment by niemyjski** [comment]
ah okay :dancer:

**Comment by gdi2290** [comment]
I updated the api and added files to be ignored for bower and npm
https://github.com/gdi2290/angular-intercom/tree/v2.0.4

**Comment by niemyjski** [comment]
Awesome thanks

**Comment by gdi2290** [comment]
np, thanks for submitting issues. If you run into any more or request a feature I can add it to the repo or you can open another PR

**Pull request merged**
